### ISSUE TITLE
Heroku Deployment 

### ISSUE THREAD

**Issue by tayyabali123** [Maher-Zubair/SIGMA-MD#16]
Yar idr se deployment stuck ho jaati hai; naa Aage jaati hai na Kuch aur.. kindly isko fix kardo 🥺
![chrome_screenshot_Feb 21, 2024 9_52_21 PM GMT+05_00](https://github.com/Maher-Zubair/SIGMA-MD/assets/147922844/3f95fc73-a20e-4458-a9c3-edc34248ec94)

**Comment by Maher-Zubair** [comment]
**_Dear User It Will Take Some Time, Kindly Have Some Patience_**

_**Also Don't Forgot To Star My Repo**_
