### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dibyenduaditya** [Maher-Zubair/SIGMA-MD#21]
npm WARN deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

**Comment by thejan007** [comment]
ya bro same problem

**Comment by Maher-Zubair** [comment]
_Dear User This Is The Npm Package Issue_
_Probably Bot Deployment Stuck There For Some Time_

_Kindy Have Some Patience, It Will Take Some Time And Be Deployed_

**Comment by thejan007** [comment]
Are you expecting a solution to this problem and how long will it take you to solve the problem?
