### ISSUE TITLE
heroku deploy error

### ISSUE THREAD

**Issue by thejan007** [Maher-Zubair/SIGMA-MD#23]
After bot update is too bad heroku deploy is building log error facing and can't create app. Plesse give me solution

**Comment by Maher-Zubair** [comment]
_Redeploy Your Bot, Watch Video https://youtu.be/HA0stB4Wuzs?si=Sue1wS2Ijfo0XR4g_

**Comment by thejan007** [comment]
![IMG_6663](https://github.com/Maher-
![IMG_6661](https://github.com/Maher-Zubair/SIGMA-MD/assets/122547565/f391d25f-c371-453c-b8b2-9632070c0834)
Zubair/SIGMA-MD/assets/122547565/b76d79d1-fcd4-4242-aa07-568e04b347f0)
![IMG_6662](https://github.com/Maher-Zubair/SIGMA-MD/assets/122547565/4d922131-929f-4f8c-a641-0a5e2a7858e4)
