### ISSUE TITLE
Mongodb url

### ISSUE THREAD

**Issue by Hammadnetwor** [Maher-Zubair/SIGMA-MD#31]
Ap ka Mongodb Url Kader Sa Copy Kara

**Comment by Hammadnetwor** [comment]
Replay

**Comment by Maher-Zubair** [comment]
_mongodb is a database for your bot, so you have to get it by your own_
_don't provide your mongodb to anyone_

_**watch this tutorial to get your mongodb url https://www.youtube.com/watch?v=HNj76uDT-uc**_
