### ISSUE TITLE
Bot not working 

### ISSUE THREAD

**Issue by Sana7649** [Maher-Zubair/SIGMA-MD#39]
Bot not working number massage only gruop werk what this problem

**Comment by Sana7649** [comment]
![Screenshot_20240321-233830](https://github.com/Maher-Zubair/SIGMA-MD/assets/162041482/7e9679e9-a7fd-4237-8980-4735e3e9613d)
![Screenshot_20240321-233806](https://github.com/Maher-Zubair/SIGMA-MD/assets/162041482/f0f7fb03-208c-4d36-8974-975ec0aaf9da)
Check now

**Comment by Sana7649** [comment]
This problem

**Comment by Maher-Zubair** [comment]
turn off reaction and restart bot app from heroku
